_default:
  just --list

start-docker:
    docker compose up --build --force-recreate -d

stop-docker:
    docker compose stop

clean-python:
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name "\.pytest_cache" -exec rm -rf {} +
    find . -type d -name "\.mypy_cache" -exec rm -rf {} +
    find . -type f -name "*.py[co]" -delete
    find . -type f -name ".DS_Store" -delete

clean-docker:
    docker compose down -v --rmi all --remove-orphans

clean-git:
    git fetch --prune
    git branch --merged | grep -v "^\*\|main" | xargs git branch -D
    git gc --aggressive

clean: clean-python clean-git
